config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

  end
  root 'posts#index'
  resources :posts
  resources :pictures, only: [:create, :destroy]
  resources :tags, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :taggings
  has_many :tags, through: :taggings

  validates :title, :summary, :body, presence: true

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger, :info, :warning

  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    {locale: I18n.locale }.merge options
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => { url: @picture.image.url(:large), picture_id: @picture.id } }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json {render json: { status: :ok} }
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [ :show, :edit, :update, :destroy ]

  def index
    @posts = Post.all
  end
  def show
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Статья успешно создана'
    else
      render :new, danger: 'Статья не создана'
    end
  end
  def edit
  end
  def update
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'Сатья успешно обновлена'
    else
      render :edit, danger: 'Статья не обновлена'
    end
  end
  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Статья успешно удалена'
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body, :image, :all_tags)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count *  (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <%= csrf_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="container-fluid" >
     <nav class="navbar navbar-expand-lg navbar-light bg-light ">
       <a class="navbar-brand" href="#">Blog</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
         <span class="sr-only">Toggle navigation</span>
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">

        </li>
          <li class="nav-item">
            <%= link_to "Рус", { locale: :ru}, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "En", { locale: :en}, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= posts_path %>">Статьи</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Контакты</a>
          </li>
        </ul>
       </div>
     </nav>
   </div>
   <div class="container main">
     <div class="row">
       <div class="col-md-12">
         <% flash.each do |name, message| %>
           <div class="alert alert-<%= name %>">
             <%= message %>
           </div>
         <% end %>
       </div>
     </div>
     <div class="row">
       <div class="col-md-9">
         <%= yield %>
       </div>
     </div>

     <div class="row">
       <div class="col-md-3">
         <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag,css_class| %>
           <%= link_to tag.name, tag_path(tag.name), class: css_class %>
         <% end %>
       </div>
     </div>
   </div>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    var disqus_config = function () {
        this.page.url = 'http://localhost.com<%= request.original_fullpath %>';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://blogdevsimple-9.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= t('common.errors')  %></h5>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form_for @post, html: {multipart: true } do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title,class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :summary %>
      <%= f.text_area :summary,class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.trix_editor :body,class: 'editor' %>
    </div>

    <div class="form-group">
      <%= f.label :all_tags %>
      <%= f.text_field :all_tags,class: 'form-control' %>
    </div>


    <div class="form-group">
      <%= f.file_field :image %>
    </div>

    <div class="form-group">
      <%= f.submit t('.submit', action: @post.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
      <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time>
      |
      <%= link_to 'Изменить', edit_post_path(post) %>
      |
      <%= link_to 'Удалить', post_path(post), method: :delete, data: { confirm: 'Вы уверены?' } %>
    </small>
  </section>

  <section class="post-summary clearfix">
   <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
   <%= post.summary %>
  </section>

  <section class="footer-summary">
    <%= raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'tag tag-primary'}.join(' ') %>
  </section>
</article>

app/views/posts/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1><%= t('.title') %></h1>

<%= render @posts  %>

app/views/posts/new.html.erb
<h1><%= t('.title') %></h1>

<%=render 'form' %>

app/views/posts/show.html.erb
<article class="post">
  <section class="post-head">
    <h1><%=  @post.title %></h1>
    <small>
      <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time>
      |
      <%= link_to 'Изменить', edit_post_path(@post) %>
      |
      <%= link_to 'Удалить', post_path(@post), method: :delete, data: { confirm: 'Вы уверены?' } %>
    </small>
  </section>

  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <%= @post.body.html_safe %>
  </section>
</article>

<%= render 'disqus' %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% if @tag.posts.empty? %>
    <h2>Статей нет</h2>
<% else %>
    <%= render @tag.posts %>
<% end %>